# Global
report_interval=15

[[endpoints]]
name = "InitialState"
url = "https://groker.init.st/api/events?accessKey=<YOURACCESSKEY>&bucketKey=<YOURBUCKETKEY>&{sensor}={temperature}"
method = "GET"

[[endpoints]]
name = "InfluxDB"
url = "https://<YOURURL>.influxdata.com/api/v2/write?org=<YOURORG>&bucket=<YOURBUCKET>&precision=s"
method = "POST"
body = "temp,location={sensor} value={temperature}"

[endpoints.headers]
Authorization = "Token <YOURTOKEN>"
Content-Type = "text/plain; charset=utf-8"
Accept = "application/json"
